In [ ]:
from PIL import Image
import cv2
import numpy as np
import pandas as pd 
import tensorflow as tf

In [ ]:
!pip install paddlepaddle-gpu==2.3.2 cudatoolkit==10.2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement cudatoolkit==10.2 (from versions: none)
ERROR: No matching distribution found for cudatoolkit==10.2


# pdf2image

## Installation

In [ ]:
!pip install pdf2image
!apt-get update
!apt-get install poppler-utils

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:3 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:5 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Hit:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:8 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:9 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Hit:11 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Get:12 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
Hit:13 http://ppa.launchpad.n

## Conversion

In [ ]:
from pdf2image import convert_from_path

In [ ]:
images = convert_from_path('/content/10.1.1.995.5264.pdf')

In [ ]:
!mkdir pages

mkdir: cannot create directory ‘pages’: File exists


In [ ]:
for i in range(len(images)):
  images[i].save('pages/page'+str(i)+'.jpg', 'JPEG')

# Layout

## Installation

In [ ]:
!python3 -m pip install paddlepaddle-gpu
!pip install "paddleocr>=2.0.1"
!pip install protobuf==3.20.0
!git clone https://github.com/PaddlePaddle/PaddleOCR.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
fatal: destination path 'PaddleOCR' already exists and is not an empty directory.


In [ ]:
a=5

In [ ]:
!wget https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl
!pip install -U layoutparser-0.0.0-py3-none-any.whl

--2022-10-12 12:03:05--  https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl
Resolving paddleocr.bj.bcebos.com (paddleocr.bj.bcebos.com)... 220.181.33.43, 220.181.33.44, 2409:8c04:1001:1002:0:ff:b001:368a
Connecting to paddleocr.bj.bcebos.com (paddleocr.bj.bcebos.com)|220.181.33.43|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19145360 (18M) [application/octet-stream]
Saving to: ‘layoutparser-0.0.0-py3-none-any.whl.3’

layoutparser-0.0.0- 100%[===================>]  18.26M  4.94MB/s    in 5.4s    

2022-10-12 12:03:12 (3.36 MB/s) - ‘layoutparser-0.0.0-py3-none-any.whl.3’ saved [19145360/19145360]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Processing ./layoutparser-0.0.0-py3-none-any.whl
layoutparser is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.


## Table Extraction

In [ ]:
import cv2
import layoutparser as lp
image = cv2.imread("/content/pages/page0.jpg")

image = image[..., ::-1]

# load model
model = lp.PaddleDetectionLayoutModel(config_path="lp://PubLayNet/ppyolov2_r50vd_dcn_365e_publaynet/config",
                                threshold=0.5,
                                label_map={0: "Text", 1: "Title", 2: "List", 3:"Table", 4:"Figure"},
                                enforce_cpu=False,
                                enable_mkldnn=True)#math kernel library
# detect
layout = model.detect(image)

In [ ]:
layout

In [ ]:
x_1=0
y_1=0
x_2=0
y_2=0

for l in layout:
  print(l)
  if l.type == 'Table':
    x_1 = int(l.block.x_1)
    print(l.block.x_1)
    y_1 = int(l.block.y_1)
    x_2 = int(l.block.x_2)
    y_2 = int(l.block.y_2)
    
    break

TextBlock(block=Rectangle(x_1=48.9151611328125, y_1=89.757568359375, x_2=1618.2166748046875, y_2=1995.265625), text=None, id=None, type=Figure, parent=None, next=None, score=0.9652584791183472)
TextBlock(block=Rectangle(x_1=52.398193359375, y_1=2068.001708984375, x_2=1264.267578125, y_2=2118.669677734375), text=None, id=None, type=Text, parent=None, next=None, score=0.8032485842704773)


In [ ]:
print(x_1,y_1,x_2,y_2)

0 0 0 0


In [ ]:
im = cv2.imread('/content/pages/page0.jpg')


In [ ]:
cv2.imwrite('ext_im.jpg', im)#[y_1:y_2,x_1:x_2])

True

# Text Detection and Recognition

In [ ]:
from paddleocr import PaddleOCR, draw_ocr

In [ ]:
ocr = PaddleOCR(lang='en')
image_path = '/content/ext_im.jpg'
image_cv = cv2.imread(image_path)
image_height = image_cv.shape[0]
image_width = image_cv.shape[1]
output = ocr.ocr(image_path)

[2022/09/29 19:11:26] ppocr DEBUG: Namespace(alpha=1.0, benchmark=False, beta=1.0, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_fce_box_type='poly', det_limit_side_len=960, det_limit_type='max', det_model_dir='/root/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_box_type='quad', det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_polygon=False, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='f

In [ ]:
print(output)

[[[[113.0, 109.0], [621.0, 135.0], [618.0, 191.0], [110.0, 165.0]], ('UBLUNITED BANK.', 0.9269370436668396)], [[[1147.0, 163.0], [1570.0, 163.0], [1570.0, 212.0], [1147.0, 212.0]], ('Account Statement', 0.9793155789375305)], [[[175.0, 229.0], [569.0, 229.0], [569.0, 253.0], [175.0, 253.0]], ('0401-BABA-E-URDU ROAD,KARACHI', 0.9543657898902893)], [[[62.0, 258.0], [266.0, 258.0], [266.0, 283.0], [62.0, 283.0]], ('NAZSH IFTIKHAR', 0.9600556492805481)], [[[955.0, 266.0], [1122.0, 266.0], [1122.0, 290.0], [955.0, 290.0]], ('Statement Period', 0.9819560647010803)], [[[1184.0, 266.0], [1524.0, 266.0], [1524.0, 290.0], [1184.0, 290.0]], ('From 01-JAN-2021To 30-APR-2021', 0.9689167737960815)], [[[62.0, 288.0], [460.0, 288.0], [460.0, 312.0], [62.0, 312.0]], ('HOUSE NO.R 86 SECRO R V GULSHAN', 0.9171682596206665)], [[[957.0, 292.0], [1085.0, 292.0], [1085.0, 319.0], [957.0, 319.0]], ('Account No:', 0.9328449368476868)], [[[1182.0, 287.0], [1322.0, 290.0], [1321.0, 317.0], [1181.0, 314.0]], ('000

In [ ]:
boxes = [line[0] for line in output]
texts = [line[1][0] for line in output]
probabilities = [line[1][1] for line in output]

In [ ]:
image_boxes = image_cv.copy()

In [ ]:
for box,text in zip(boxes,texts):
  cv2.rectangle(image_boxes, (int(box[0][0]),int(box[0][1])), (int(box[2][0]),int(box[2][1])),(0,0,255),1)
  cv2.putText(image_boxes, text,(int(box[0][0]),int(box[0][1])),cv2.FONT_HERSHEY_SIMPLEX,1,(222,0,0),1)

In [ ]:
cv2.imwrite('detections.jpg', image_boxes)

True

# Reconstruction

## Get Horizontal and Vertical Lines

In [ ]:
im = image_cv.copy()

In [ ]:
horiz_boxes = []
vert_boxes = []

for box in boxes:
  x_h, x_v = 0,int(box[0][0])
  y_h, y_v = int(box[0][1]),0
  width_h,width_v = image_width, int(box[2][0]-box[0][0])
  height_h,height_v = int(box[2][1]-box[0][1]),image_height

  horiz_boxes.append([x_h,y_h,x_h+width_h,y_h+height_h])
  vert_boxes.append([x_v,y_v,x_v+width_v,y_v+height_v])

  cv2.rectangle(im,(x_h,y_h), (x_h+width_h,y_h+height_h),(0,0,255),1)
  cv2.rectangle(im,(x_v,y_v), (x_v+width_v,y_v+height_v),(0,255,0),1)
  

In [ ]:
cv2.imwrite('horiz_vert.jpg',im)

True

## Non-Max Suppression

In [ ]:
horiz_out = tf.image.non_max_suppression(
    horiz_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)

In [ ]:
horiz_lines = np.sort(np.array(horiz_out))
print(horiz_lines)

[ 0  2  3  4  5  7  8 11 12 14 17 22 24 25 26 28 30 31 32 33 35 38 40 42]


In [ ]:
im_nms = image_cv.copy()

In [ ]:
for val in horiz_lines:
  cv2.rectangle(im_nms, (int(horiz_boxes[val][0]),int(horiz_boxes[val][1])), (int(horiz_boxes[val][2]),int(horiz_boxes[val][3])),(0,0,255),1)
  

In [ ]:
cv2.imwrite('im_nms.jpg',im_nms)

True

In [ ]:
vert_out = tf.image.non_max_suppression(
    vert_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)

In [ ]:
print(vert_out)

tf.Tensor([22 40 29 33 18 15], shape=(6,), dtype=int32)


In [ ]:
vert_lines = np.sort(np.array(vert_out))
print(vert_lines)

[15 18 22 29 33 40]


In [ ]:
for val in vert_lines:
  cv2.rectangle(im_nms, (int(vert_boxes[val][0]),int(vert_boxes[val][1])), (int(vert_boxes[val][2]),int(vert_boxes[val][3])),(255,0,0),1)
  

In [ ]:
cv2.imwrite('im_nms.jpg',im_nms)

True

## Convert to CSV

In [ ]:
out_array = [["" for i in range(len(vert_lines))] for j in range(len(horiz_lines))]
print(np.array(out_array).shape)
print(out_array)

(24, 6)
[['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', '']]


In [ ]:
unordered_boxes = []

for i in vert_lines:
  print(vert_boxes[i])
  unordered_boxes.append(vert_boxes[i][0])

[994, 0, 1090, 2336]
[435, 0, 600, 2336]
[1437, 0, 1532, 2336]
[1215, 0, 1328, 2336]
[116, 0, 337, 2336]
[748, 0, 900, 2336]


In [ ]:
ordered_boxes = np.argsort(unordered_boxes)
print(ordered_boxes)

[4 1 5 0 3 2]


In [ ]:
def intersection(box_1, box_2):
  return [box_2[0], box_1[1],box_2[2], box_1[3]]

In [ ]:
def iou(box_1, box_2):

  x_1 = max(box_1[0], box_2[0])
  y_1 = max(box_1[1], box_2[1])
  x_2 = min(box_1[2], box_2[2])
  y_2 = min(box_1[3], box_2[3])

  inter = abs(max((x_2 - x_1, 0)) * max((y_2 - y_1), 0))
  if inter == 0:
      return 0
      
  box_1_area = abs((box_1[2] - box_1[0]) * (box_1[3] - box_1[1]))
  box_2_area = abs((box_2[2] - box_2[0]) * (box_2[3] - box_2[1]))
  
  return inter / float(box_1_area + box_2_area - inter)

In [ ]:
for i in range(len(horiz_lines)):
  for j in range(len(vert_lines)):
    resultant = intersection(horiz_boxes[horiz_lines[i]], vert_boxes[vert_lines[ordered_boxes[j]]] )

    for b in range(len(boxes)):
      the_box = [boxes[b][0][0],boxes[b][0][1],boxes[b][2][0],boxes[b][2][1]]
      if(iou(resultant,the_box)>0.1):
        out_array[i][j] = texts[b]

In [ ]:
out_array=np.array(out_array)

In [ ]:
out_array

array([['Mayne Maps', '', '', '', '', 'INVOICE'],
       ['ABN 4981 5250 249', '', '', '', '', ''],
       ['349 Fig Tree Pocket Road', '', '', '', '', ''],
       ['Fig Tree Pocket 4069', '', '', '', '', ''],
       ['Phone 0409 800 211', '', '', '', '', 'INVOICE #2104'],
       ['alan53au@yahoo.com.au', '', '', '', '', 'INVOICE #2104'],
       ['ABN:4981 5250 249', '', '', '', 'DATE: AUGUST 31ST, 2022',
        'DATE: AUGUST 31ST, 2022'],
       ['TO:', '', 'FOR', '', '', ''],
       ['Ms Amanda Milton', '', 'Map production for "NEWLAND"',
        'Map production for "NEWLAND"', 'Map production for "NEWLAND"',
        ''],
       ['Elders', '', '', '', '', ''],
       ['', 'DESCRIPTION', '', 'HOURS', 'RATE', 'AMOUNT'],
       ['6-7/8/2022 Map production for "NEWLANDS"',
        '6-7/8/2022 Map production for "NEWLANDS"', '', '4.75 hours',
        '$40 /hr', '$190.00'],
       ['GST COMPONENT', '', '', '', '', '$19.00'],
       ['', 'INVOICE NUMBER #2104', 'INVOICE NUMBER #2104', '', 

In [ ]:
pd.DataFrame(out_array).to_csv('sample.csv')

## Merging Cells

In [ ]:
current_bank=['']*len(out_array[0,:])
print(current_bank)

['', '', '', '', '', '']


In [ ]:
def empty(arr):
  for i in arr:
    if i=='':
      return True
  return False

In [ ]:
cleaned_array=[]

In [ ]:
for i in range(len(out_array)):
  if not empty(out_array[i]):
    current_bank=[out_array[i][j] for j in range(len(out_array[i]))]
    cleaned_array.append(current_bank)
    not_empty=True
  else:
    for j in range(len(out_array[i])):
      current_bank[j]+=' '+out_array[i][j]
    print('-->',current_bank)
cleaned_array=np.array(cleaned_array)
print(cleaned_array)

--> [' Mayne Maps', ' ', ' ', ' ', ' ', ' INVOICE']
--> [' Mayne Maps ABN 4981 5250 249', '  ', '  ', '  ', '  ', ' INVOICE ']
--> [' Mayne Maps ABN 4981 5250 249 349 Fig Tree Pocket Road', '   ', '   ', '   ', '   ', ' INVOICE  ']
--> [' Mayne Maps ABN 4981 5250 249 349 Fig Tree Pocket Road Fig Tree Pocket 4069', '    ', '    ', '    ', '    ', ' INVOICE   ']
--> [' Mayne Maps ABN 4981 5250 249 349 Fig Tree Pocket Road Fig Tree Pocket 4069 Phone 0409 800 211', '     ', '     ', '     ', '     ', ' INVOICE    INVOICE #2104']
--> [' Mayne Maps ABN 4981 5250 249 349 Fig Tree Pocket Road Fig Tree Pocket 4069 Phone 0409 800 211 alan53au@yahoo.com.au', '      ', '      ', '      ', '      ', ' INVOICE    INVOICE #2104 INVOICE #2104']
--> [' Mayne Maps ABN 4981 5250 249 349 Fig Tree Pocket Road Fig Tree Pocket 4069 Phone 0409 800 211 alan53au@yahoo.com.au ABN:4981 5250 249', '       ', '       ', '       ', '       DATE: AUGUST 31ST, 2022', ' INVOICE    INVOICE #2104 INVOICE #2104 DATE: AUGU

In [ ]:
pd.DataFrame(cleaned_array).to_csv('cleaned.csv')

# Convert to OWL Format

# **CSV to Text**

In [ ]:
import  jpype     
import  asposecells  


jpype.startJVM() 
from asposecells.api import Workbook

workbook = Workbook("/content/sample.csv")
workbook.save("Output.docx")
jpype.shutdownJVM()

# Brighten Image (For Anyone dealing with PDFs created from scanned images)

In [ ]:
from PIL import Image, ImageEnhance

#read the image
im = Image.open("ext_im.jpg")

#image brightness enhancer
enhancer = ImageEnhance.Brightness(im)

factor = 1 #gives original image
im_output = enhancer.enhance(factor)
im_output.save('ext_im-1.jpg')

factor = 1.5## brightens the image
im_output = enhancer.enhance(factor)
im_output.save('ext_im-2.jpg')
